// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjNRGqmEEEx-u6eIfcxfsS6-KopIWKTU',
    appId: '1:356131257938:web:e6393b202e0749b757e98b',
    messagingSenderId: '356131257938',
    projectId: 'notetakingapp-19352',
    authDomain: 'notetakingapp-19352.firebaseapp.com',
    storageBucket: 'notetakingapp-19352.firebasestorage.app',
    measurementId: 'G-K9PL1PZH13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmibWatSHE1NhWJCA45z4CoESzGdwn52k',
    appId: '1:356131257938:android:49b84af68011a68357e98b',
    messagingSenderId: '356131257938',
    projectId: 'notetakingapp-19352',
    storageBucket: 'notetakingapp-19352.firebasestorage.app',
  );
}
